//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GREENPLY.GreenplyERPPostingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="GreenplyERPPostingService.Zbc_tst_ws")]
    public interface Zbc_tst_ws {
        
        // CODEGEN: Generating message contract since the operation ZbcPlyqrCodePost is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:Zbc_tst_ws:ZbcPlyqrCodePostReque" +
            "st", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GREENPLY.GreenplyERPPostingService.ZbcPlyqrCodePostResponse1 ZbcPlyqrCodePost(GREENPLY.GreenplyERPPostingService.ZbcPlyqrCodePostRequest request);
        
        // CODEGEN: Generating message contract since the operation ZbcDeliveryOrderPost is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:Zbc_tst_ws:ZbcDeliveryOrderPostR" +
            "equest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GREENPLY.GreenplyERPPostingService.ZbcDeliveryOrderPostResponse1 ZbcDeliveryOrderPost(GREENPLY.GreenplyERPPostingService.ZbcDeliveryOrderPostRequest request);
        
        // CODEGEN: Generating message contract since the operation ZbcVendorPrintPost is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:Zbc_tst_ws:ZbcVendorPrintPostReq" +
            "uest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GREENPLY.GreenplyERPPostingService.ZbcVendorPrintPostResponse1 ZbcVendorPrintPost(GREENPLY.GreenplyERPPostingService.ZbcVendorPrintPostRequest request);
        
        // CODEGEN: Generating message contract since the operation ZbcDelvOrderPostRet is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:Zbc_tst_ws:ZbcDelvOrderPostRetRe" +
            "quest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GREENPLY.GreenplyERPPostingService.ZbcDelvOrderPostRetResponse1 ZbcDelvOrderPostRet(GREENPLY.GreenplyERPPostingService.ZbcDelvOrderPostRetRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZbcPlyqrCodePost : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZstrBcMatPost[] dataInField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZstrBcMatPost[] DataIn {
            get {
                return this.dataInField;
            }
            set {
                this.dataInField = value;
                this.RaisePropertyChanged("DataIn");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZstrBcMatPost : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string plantcodeField;
        
        private string matcodeField;
        
        private string serialField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Plantcode {
            get {
                return this.plantcodeField;
            }
            set {
                this.plantcodeField = value;
                this.RaisePropertyChanged("Plantcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Matcode {
            get {
                return this.matcodeField;
            }
            set {
                this.matcodeField = value;
                this.RaisePropertyChanged("Matcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Serial {
            get {
                return this.serialField;
            }
            set {
                this.serialField = value;
                this.RaisePropertyChanged("Serial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZstrBcVenPrintPostOut : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string plantcodeField;
        
        private string ponumField;
        
        private string vendinvnoField;
        
        private string vendinvdtField;
        
        private string vendcodeField;
        
        private string matcodeField;
        
        private string poqtyField;
        
        private string serialField;
        
        private string stsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Plantcode {
            get {
                return this.plantcodeField;
            }
            set {
                this.plantcodeField = value;
                this.RaisePropertyChanged("Plantcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Ponum {
            get {
                return this.ponumField;
            }
            set {
                this.ponumField = value;
                this.RaisePropertyChanged("Ponum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Vendinvno {
            get {
                return this.vendinvnoField;
            }
            set {
                this.vendinvnoField = value;
                this.RaisePropertyChanged("Vendinvno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Vendinvdt {
            get {
                return this.vendinvdtField;
            }
            set {
                this.vendinvdtField = value;
                this.RaisePropertyChanged("Vendinvdt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Vendcode {
            get {
                return this.vendcodeField;
            }
            set {
                this.vendcodeField = value;
                this.RaisePropertyChanged("Vendcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Matcode {
            get {
                return this.matcodeField;
            }
            set {
                this.matcodeField = value;
                this.RaisePropertyChanged("Matcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Poqty {
            get {
                return this.poqtyField;
            }
            set {
                this.poqtyField = value;
                this.RaisePropertyChanged("Poqty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Serial {
            get {
                return this.serialField;
            }
            set {
                this.serialField = value;
                this.RaisePropertyChanged("Serial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Sts {
            get {
                return this.stsField;
            }
            set {
                this.stsField = value;
                this.RaisePropertyChanged("Sts");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZstrBcVenPrintPost : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string plantcodeField;
        
        private string ponumField;
        
        private string vendinvnoField;
        
        private string vendinvdtField;
        
        private string vendcodeField;
        
        private string matcodeField;
        
        private string poqtyField;
        
        private string serialField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Plantcode {
            get {
                return this.plantcodeField;
            }
            set {
                this.plantcodeField = value;
                this.RaisePropertyChanged("Plantcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Ponum {
            get {
                return this.ponumField;
            }
            set {
                this.ponumField = value;
                this.RaisePropertyChanged("Ponum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Vendinvno {
            get {
                return this.vendinvnoField;
            }
            set {
                this.vendinvnoField = value;
                this.RaisePropertyChanged("Vendinvno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Vendinvdt {
            get {
                return this.vendinvdtField;
            }
            set {
                this.vendinvdtField = value;
                this.RaisePropertyChanged("Vendinvdt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Vendcode {
            get {
                return this.vendcodeField;
            }
            set {
                this.vendcodeField = value;
                this.RaisePropertyChanged("Vendcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Matcode {
            get {
                return this.matcodeField;
            }
            set {
                this.matcodeField = value;
                this.RaisePropertyChanged("Matcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Poqty {
            get {
                return this.poqtyField;
            }
            set {
                this.poqtyField = value;
                this.RaisePropertyChanged("Poqty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Serial {
            get {
                return this.serialField;
            }
            set {
                this.serialField = value;
                this.RaisePropertyChanged("Serial");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZstrSdBcDelvPostOut : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string plantcodeField;
        
        private string deliverynoField;
        
        private string matcodeField;
        
        private string serialField;
        
        private string qtyField;
        
        private string stsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Plantcode {
            get {
                return this.plantcodeField;
            }
            set {
                this.plantcodeField = value;
                this.RaisePropertyChanged("Plantcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Deliveryno {
            get {
                return this.deliverynoField;
            }
            set {
                this.deliverynoField = value;
                this.RaisePropertyChanged("Deliveryno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Matcode {
            get {
                return this.matcodeField;
            }
            set {
                this.matcodeField = value;
                this.RaisePropertyChanged("Matcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Serial {
            get {
                return this.serialField;
            }
            set {
                this.serialField = value;
                this.RaisePropertyChanged("Serial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
                this.RaisePropertyChanged("Qty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Sts {
            get {
                return this.stsField;
            }
            set {
                this.stsField = value;
                this.RaisePropertyChanged("Sts");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZstrSdBcDelvPost : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string plantcodeField;
        
        private string deliverynoField;
        
        private string matcodeField;
        
        private string serialField;
        
        private string qtyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Plantcode {
            get {
                return this.plantcodeField;
            }
            set {
                this.plantcodeField = value;
                this.RaisePropertyChanged("Plantcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Deliveryno {
            get {
                return this.deliverynoField;
            }
            set {
                this.deliverynoField = value;
                this.RaisePropertyChanged("Deliveryno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Matcode {
            get {
                return this.matcodeField;
            }
            set {
                this.matcodeField = value;
                this.RaisePropertyChanged("Matcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Serial {
            get {
                return this.serialField;
            }
            set {
                this.serialField = value;
                this.RaisePropertyChanged("Serial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
                this.RaisePropertyChanged("Qty");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZstrBcMatPostOut : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string plantcodeField;
        
        private string matcodeField;
        
        private string serialField;
        
        private string statusField;
        
        private string stsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Plantcode {
            get {
                return this.plantcodeField;
            }
            set {
                this.plantcodeField = value;
                this.RaisePropertyChanged("Plantcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Matcode {
            get {
                return this.matcodeField;
            }
            set {
                this.matcodeField = value;
                this.RaisePropertyChanged("Matcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Serial {
            get {
                return this.serialField;
            }
            set {
                this.serialField = value;
                this.RaisePropertyChanged("Serial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Sts {
            get {
                return this.stsField;
            }
            set {
                this.stsField = value;
                this.RaisePropertyChanged("Sts");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZbcPlyqrCodePostResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZstrBcMatPostOut[] dataOutField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZstrBcMatPostOut[] DataOut {
            get {
                return this.dataOutField;
            }
            set {
                this.dataOutField = value;
                this.RaisePropertyChanged("DataOut");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZbcPlyqrCodePostRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public GREENPLY.GreenplyERPPostingService.ZbcPlyqrCodePost ZbcPlyqrCodePost;
        
        public ZbcPlyqrCodePostRequest() {
        }
        
        public ZbcPlyqrCodePostRequest(GREENPLY.GreenplyERPPostingService.ZbcPlyqrCodePost ZbcPlyqrCodePost) {
            this.ZbcPlyqrCodePost = ZbcPlyqrCodePost;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZbcPlyqrCodePostResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public GREENPLY.GreenplyERPPostingService.ZbcPlyqrCodePostResponse ZbcPlyqrCodePostResponse;
        
        public ZbcPlyqrCodePostResponse1() {
        }
        
        public ZbcPlyqrCodePostResponse1(GREENPLY.GreenplyERPPostingService.ZbcPlyqrCodePostResponse ZbcPlyqrCodePostResponse) {
            this.ZbcPlyqrCodePostResponse = ZbcPlyqrCodePostResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZbcDeliveryOrderPost : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZstrSdBcDelvPost[] dataInField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZstrSdBcDelvPost[] DataIn {
            get {
                return this.dataInField;
            }
            set {
                this.dataInField = value;
                this.RaisePropertyChanged("DataIn");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZbcDeliveryOrderPostResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZstrSdBcDelvPostOut[] dataOutField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZstrSdBcDelvPostOut[] DataOut {
            get {
                return this.dataOutField;
            }
            set {
                this.dataOutField = value;
                this.RaisePropertyChanged("DataOut");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZbcDeliveryOrderPostRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public GREENPLY.GreenplyERPPostingService.ZbcDeliveryOrderPost ZbcDeliveryOrderPost;
        
        public ZbcDeliveryOrderPostRequest() {
        }
        
        public ZbcDeliveryOrderPostRequest(GREENPLY.GreenplyERPPostingService.ZbcDeliveryOrderPost ZbcDeliveryOrderPost) {
            this.ZbcDeliveryOrderPost = ZbcDeliveryOrderPost;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZbcDeliveryOrderPostResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public GREENPLY.GreenplyERPPostingService.ZbcDeliveryOrderPostResponse ZbcDeliveryOrderPostResponse;
        
        public ZbcDeliveryOrderPostResponse1() {
        }
        
        public ZbcDeliveryOrderPostResponse1(GREENPLY.GreenplyERPPostingService.ZbcDeliveryOrderPostResponse ZbcDeliveryOrderPostResponse) {
            this.ZbcDeliveryOrderPostResponse = ZbcDeliveryOrderPostResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZbcVendorPrintPost : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZstrBcVenPrintPost[] dataInField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZstrBcVenPrintPost[] DataIn {
            get {
                return this.dataInField;
            }
            set {
                this.dataInField = value;
                this.RaisePropertyChanged("DataIn");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZbcVendorPrintPostResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZstrBcVenPrintPostOut[] dataOutField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZstrBcVenPrintPostOut[] DataOut {
            get {
                return this.dataOutField;
            }
            set {
                this.dataOutField = value;
                this.RaisePropertyChanged("DataOut");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZbcVendorPrintPostRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public GREENPLY.GreenplyERPPostingService.ZbcVendorPrintPost ZbcVendorPrintPost;
        
        public ZbcVendorPrintPostRequest() {
        }
        
        public ZbcVendorPrintPostRequest(GREENPLY.GreenplyERPPostingService.ZbcVendorPrintPost ZbcVendorPrintPost) {
            this.ZbcVendorPrintPost = ZbcVendorPrintPost;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZbcVendorPrintPostResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public GREENPLY.GreenplyERPPostingService.ZbcVendorPrintPostResponse ZbcVendorPrintPostResponse;
        
        public ZbcVendorPrintPostResponse1() {
        }
        
        public ZbcVendorPrintPostResponse1(GREENPLY.GreenplyERPPostingService.ZbcVendorPrintPostResponse ZbcVendorPrintPostResponse) {
            this.ZbcVendorPrintPostResponse = ZbcVendorPrintPostResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZbcDelvOrderPostRet : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZstrSdBcDelvPost[] dataInField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZstrSdBcDelvPost[] DataIn {
            get {
                return this.dataInField;
            }
            set {
                this.dataInField = value;
                this.RaisePropertyChanged("DataIn");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZbcDelvOrderPostRetResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZstrSdBcDelvPostOut[] dataOutField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZstrSdBcDelvPostOut[] DataOut {
            get {
                return this.dataOutField;
            }
            set {
                this.dataOutField = value;
                this.RaisePropertyChanged("DataOut");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZbcDelvOrderPostRetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public GREENPLY.GreenplyERPPostingService.ZbcDelvOrderPostRet ZbcDelvOrderPostRet;
        
        public ZbcDelvOrderPostRetRequest() {
        }
        
        public ZbcDelvOrderPostRetRequest(GREENPLY.GreenplyERPPostingService.ZbcDelvOrderPostRet ZbcDelvOrderPostRet) {
            this.ZbcDelvOrderPostRet = ZbcDelvOrderPostRet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZbcDelvOrderPostRetResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public GREENPLY.GreenplyERPPostingService.ZbcDelvOrderPostRetResponse ZbcDelvOrderPostRetResponse;
        
        public ZbcDelvOrderPostRetResponse1() {
        }
        
        public ZbcDelvOrderPostRetResponse1(GREENPLY.GreenplyERPPostingService.ZbcDelvOrderPostRetResponse ZbcDelvOrderPostRetResponse) {
            this.ZbcDelvOrderPostRetResponse = ZbcDelvOrderPostRetResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Zbc_tst_wsChannel : GREENPLY.GreenplyERPPostingService.Zbc_tst_ws, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Zbc_tst_wsClient : System.ServiceModel.ClientBase<GREENPLY.GreenplyERPPostingService.Zbc_tst_ws>, GREENPLY.GreenplyERPPostingService.Zbc_tst_ws {
        
        public Zbc_tst_wsClient() {
        }
        
        public Zbc_tst_wsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Zbc_tst_wsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Zbc_tst_wsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Zbc_tst_wsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GREENPLY.GreenplyERPPostingService.ZbcPlyqrCodePostResponse1 GREENPLY.GreenplyERPPostingService.Zbc_tst_ws.ZbcPlyqrCodePost(GREENPLY.GreenplyERPPostingService.ZbcPlyqrCodePostRequest request) {
            return base.Channel.ZbcPlyqrCodePost(request);
        }
        
        public GREENPLY.GreenplyERPPostingService.ZbcPlyqrCodePostResponse ZbcPlyqrCodePost(GREENPLY.GreenplyERPPostingService.ZbcPlyqrCodePost ZbcPlyqrCodePost1) {
            GREENPLY.GreenplyERPPostingService.ZbcPlyqrCodePostRequest inValue = new GREENPLY.GreenplyERPPostingService.ZbcPlyqrCodePostRequest();
            inValue.ZbcPlyqrCodePost = ZbcPlyqrCodePost1;
            GREENPLY.GreenplyERPPostingService.ZbcPlyqrCodePostResponse1 retVal = ((GREENPLY.GreenplyERPPostingService.Zbc_tst_ws)(this)).ZbcPlyqrCodePost(inValue);
            return retVal.ZbcPlyqrCodePostResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GREENPLY.GreenplyERPPostingService.ZbcDeliveryOrderPostResponse1 GREENPLY.GreenplyERPPostingService.Zbc_tst_ws.ZbcDeliveryOrderPost(GREENPLY.GreenplyERPPostingService.ZbcDeliveryOrderPostRequest request) {
            return base.Channel.ZbcDeliveryOrderPost(request);
        }
        
        public GREENPLY.GreenplyERPPostingService.ZbcDeliveryOrderPostResponse ZbcDeliveryOrderPost(GREENPLY.GreenplyERPPostingService.ZbcDeliveryOrderPost ZbcDeliveryOrderPost1) {
            GREENPLY.GreenplyERPPostingService.ZbcDeliveryOrderPostRequest inValue = new GREENPLY.GreenplyERPPostingService.ZbcDeliveryOrderPostRequest();
            inValue.ZbcDeliveryOrderPost = ZbcDeliveryOrderPost1;
            GREENPLY.GreenplyERPPostingService.ZbcDeliveryOrderPostResponse1 retVal = ((GREENPLY.GreenplyERPPostingService.Zbc_tst_ws)(this)).ZbcDeliveryOrderPost(inValue);
            return retVal.ZbcDeliveryOrderPostResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GREENPLY.GreenplyERPPostingService.ZbcVendorPrintPostResponse1 GREENPLY.GreenplyERPPostingService.Zbc_tst_ws.ZbcVendorPrintPost(GREENPLY.GreenplyERPPostingService.ZbcVendorPrintPostRequest request) {
            return base.Channel.ZbcVendorPrintPost(request);
        }
        
        public GREENPLY.GreenplyERPPostingService.ZbcVendorPrintPostResponse ZbcVendorPrintPost(GREENPLY.GreenplyERPPostingService.ZbcVendorPrintPost ZbcVendorPrintPost1) {
            GREENPLY.GreenplyERPPostingService.ZbcVendorPrintPostRequest inValue = new GREENPLY.GreenplyERPPostingService.ZbcVendorPrintPostRequest();
            inValue.ZbcVendorPrintPost = ZbcVendorPrintPost1;
            GREENPLY.GreenplyERPPostingService.ZbcVendorPrintPostResponse1 retVal = ((GREENPLY.GreenplyERPPostingService.Zbc_tst_ws)(this)).ZbcVendorPrintPost(inValue);
            return retVal.ZbcVendorPrintPostResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GREENPLY.GreenplyERPPostingService.ZbcDelvOrderPostRetResponse1 GREENPLY.GreenplyERPPostingService.Zbc_tst_ws.ZbcDelvOrderPostRet(GREENPLY.GreenplyERPPostingService.ZbcDelvOrderPostRetRequest request) {
            return base.Channel.ZbcDelvOrderPostRet(request);
        }
        
        public GREENPLY.GreenplyERPPostingService.ZbcDelvOrderPostRetResponse ZbcDelvOrderPostRet(GREENPLY.GreenplyERPPostingService.ZbcDelvOrderPostRet ZbcDelvOrderPostRet1) {
            GREENPLY.GreenplyERPPostingService.ZbcDelvOrderPostRetRequest inValue = new GREENPLY.GreenplyERPPostingService.ZbcDelvOrderPostRetRequest();
            inValue.ZbcDelvOrderPostRet = ZbcDelvOrderPostRet1;
            GREENPLY.GreenplyERPPostingService.ZbcDelvOrderPostRetResponse1 retVal = ((GREENPLY.GreenplyERPPostingService.Zbc_tst_ws)(this)).ZbcDelvOrderPostRet(inValue);
            return retVal.ZbcDelvOrderPostRetResponse;
        }
    }
}
